---
apiVersion: v1
kind: Secret
metadata:
  name: store-credentials
stringData:
  store-secret.yaml: |
    type: S3
    config:
      bucket: "{{ .Values.aws.bucket}}"
      region: "{{ .Values.aws.region }}"
      # access_key: ""
      # secret_key: ""
      endpoint: "s3.{{ .Values.aws.region }}.amazonaws.com"
      signature_version2: false
